// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6VlHF9y6mvz7q_t5dxYA0NlIAcGqu2ow',
    appId: '1:763682210661:web:d9cb1c7fc53c1cd795d78c',
    messagingSenderId: '763682210661',
    projectId: 'basicproject-95e20',
    authDomain: 'basicproject-95e20.firebaseapp.com',
    databaseURL: 'https://basicproject-95e20-default-rtdb.firebaseio.com',
    storageBucket: 'basicproject-95e20.firebasestorage.app',
    measurementId: 'G-RHCFS7YQK4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxhRiu_B_CUW8xUijs-AkgWpZ4rEP4qdA',
    appId: '1:763682210661:android:51c2d68c05061f2295d78c',
    messagingSenderId: '763682210661',
    projectId: 'basicproject-95e20',
    databaseURL: 'https://basicproject-95e20-default-rtdb.firebaseio.com',
    storageBucket: 'basicproject-95e20.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaVRyUpBIC4RlRjnN4B7WOoYowDufyCqs',
    appId: '1:763682210661:ios:6f09e19ff8afce1c95d78c',
    messagingSenderId: '763682210661',
    projectId: 'basicproject-95e20',
    databaseURL: 'https://basicproject-95e20-default-rtdb.firebaseio.com',
    storageBucket: 'basicproject-95e20.firebasestorage.app',
    iosBundleId: 'com.example.amsengPlanner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCaVRyUpBIC4RlRjnN4B7WOoYowDufyCqs',
    appId: '1:763682210661:ios:6f09e19ff8afce1c95d78c',
    messagingSenderId: '763682210661',
    projectId: 'basicproject-95e20',
    databaseURL: 'https://basicproject-95e20-default-rtdb.firebaseio.com',
    storageBucket: 'basicproject-95e20.firebasestorage.app',
    iosBundleId: 'com.example.amsengPlanner',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB6VlHF9y6mvz7q_t5dxYA0NlIAcGqu2ow',
    appId: '1:763682210661:web:40ce3db66d45839195d78c',
    messagingSenderId: '763682210661',
    projectId: 'basicproject-95e20',
    authDomain: 'basicproject-95e20.firebaseapp.com',
    databaseURL: 'https://basicproject-95e20-default-rtdb.firebaseio.com',
    storageBucket: 'basicproject-95e20.firebasestorage.app',
    measurementId: 'G-D87N62PR75',
  );
}
